- hosts: localhost
  gather_facts: no

  vars: 
    docker_id: hooong2
    docker_key: c94740f6-de78-4573-9190-8fdd313bd04c
    container_name: myweb
    image_name: "{{ docker_id }}/goorm-myweb"

  tasks:
  - block:
    - name: Login to Docker Hub
      docker_login:
        username: "{{ docker_id }}"
        password: "{{ docker_key }}"
        state: present
    - name: Image Build with WAR
      docker_image:
        build:
          path: .
          rm: yes
        name: "{{ image_name }}"
        push: yes
    - name: Create/Start Container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        exposed_ports:
          - "8080:8080"
        pull: yes
        recreate: yes
        state: started
    always:
    - name: Logout to Docker Hub
      docker_login:
        username: "{{ docker_id }}"
        state: absent

