- hosts: docker
  gather_facts: no

  vars:
    docker_id: hooong2
    container_name: myweb
    image_name: "{{ docker_id }}/goorm-myweb"

  tasks:
    - name: Create/Start Container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        published_ports:
          - "8080:8080"
        pull: yes
        recreate: yes
        state: started
